name: run main.py

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows manual trigger


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository content
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install and Start ClickHouse
      - name: Install and Start ClickHouse
        run: |
          sudo apt-get update
          sudo apt-get install -y clickhouse-server clickhouse-client
          sudo systemctl start clickhouse-server
          sudo systemctl status clickhouse-server

      # Verify ClickHouse is Running
      - name: Verify ClickHouse
        run: curl http://localhost:8123

      # Execute Python script
      - name: Execute script
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python main.py

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add status.log || echo "No logs to add"
          git diff-index --quiet HEAD || git commit -m "Updated logs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
